import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AudioProvider from "@/providers/AudioProvider";


const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin']
})



export const metadata: Metadata = {
  title: "Iswara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <AudioProvider>
        <body
          className={`${poppins.className} antialiased  bg-black  text-white relative`}
        >
          
        {children}
          
        </body>
      </AudioProvider>
    </html>
    
  );
}
